  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"



  [[main]]
  name = "Activities"
  weight = 400
  identifier = "activities"
  url = "/activities/"



  [[main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"
  url = "/accomplishments/"



